name: build

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
      - name: Test
        run: npm run test
      - name: Update language
        run: |
          sudo add-apt-repository -y ppa:macaulay2/macaulay2
          sudo apt-get -y --no-install-recommends install macaulay2
          npm run update
