name: build and test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          npm install
          npm run build
      - name: test
        run: npm run test
      - name: bundle
        run: npm run bundle
      - name: update
        run: |
          sudo add-apt-repository -y ppa:macaulay2/macaulay2
          sudo apt-get -y install macaulay2
          npm run update
